version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - ./config.json:/app/config.json
    environment:
      - PYTHONPATH=/app/module